randomize: true

# Total time steps
iterations: 2500

# N, L, eta
totalParticles: 30
boardLength: 20.0
eta: 0.5
absV: 0.03

# Archivos de entrada
staticFile: "sds-tp2/src/main/resources/newStatic.txt"
dynamicFile: "sds-tp2/src/main/resources/newDynamic.txt"

# Rc y condición de borde
radius: 1.0
periodicOutline: true

# Configuraciones para el benchmark
benchmark:
  particles:
    - 10
    - 100
    - 400
  simulations: 50

densityBenchmark:
  maxDensity: 10.0
  simulations: 50

# Default: particles.xyz
fileName: "va-vs-density-noise-1"
