randomize: true

# Total time steps
iterations: 1000

# N, L, eta
totalParticles: 100
boardLength: 7.0
eta: 2.0
absV: 0.03

# Archivos de entrada
staticFile: "sds-tp2/src/main/resources/newStatic.txt"
dynamicFile: "sds-tp2/src/main/resources/newDynamic.txt"

# Rc y condición de borde
radius: 0.1
periodicOutline: true

# Configuraciones para el benchmark
benchmark:
  particles:
    - 10
    - 100
    - 400
  simulations: 50

# Default: output.txt
fileName: ""