randomize: true

# Total time steps
iterations: 300

# N, L, eta
totalParticles: 10
boardLength: 50.0
eta: 2.0
absV: 1.3

# Archivos de entrada
staticFile: "sds-tp2/src/main/resources/newStatic.txt"
dynamicFile: "sds-tp2/src/main/resources/newDynamic.txt"

# Rc y condición de borde
radius: 7.0
periodicOutline: true

# Default: output.txt
fileName: ""